{% set name = "imagecodecs" %}
{% set version = "2023.1.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1b4591839a2f5c90467e50ebe54117cbd9be42c18864abdf85fc7743223ac5b2
  patches:
    - 0001-remove-blosc2-codec.patch
    - 0002-patch-aarch64-s390x-codecs.patch   # [s390x or aarch64]

build:
  skip: true   # [py<38]
  number: 0
  entry_points:
    - imagecodecs=imagecodecs.__main__:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - m2w64-toolchain  # [win]
    - patch            # [unix]
    - m2-patch         # [win]
  host:
    # - setuptools
    # - m2w64-pkg-config 0.29.1  # [win]
    - python
    - pip
    - numpy-devel {{ numpy }}  # [not (osx and arm64) and py<=39]
    - numpy {{ numpy }}        # [(osx and arm64) or py>39]
    - cython 0.29.35
    - zlib {{ zlib }}
    - bzip2 {{ bzip2 }}
    - xz {{ xz }}
    - zstd {{ zstd }}
    - lz4-c 1.9.4
    - libpng {{ libpng }}
    - libwebp {{ libwebp }}
    - libwebp-base 1.2.4
    - jxrlib 1.1
    - jpeg {{ jpeg }}
    - giflib {{ giflib }}
    - openjpeg {{ openjpeg }}
    - blosc 1.21.3
    - c-blosc2 2.8.0
    - lcms2 2.12               # [not win32]
    - libaec 1.0.4
    - brotli 1.0.9
    - libzopfli 1.0.3
    - charls 2.2.0            # [not s390x]
    - snappy 1.1.9
    - libtiff 4.5.0
    - lerc 3                  # [not s390x]
    - zfp 1.0.0               # [not (s390x or aarch64)]
    - libdeflate 1.17
    - brunsli 0.1             # [not win and not s390x]
    # While jpeg-turbo is the preferred version upstream, the migration
    # to libjpeg-turbo has been contentious on conda-forge
    # - libjpeg-turbo
    - cfitsio 3.470
    - wheel
  run:
    - libdeflate >=1.17,<1.18.0a0
    - python
    # Work around missing `run_exports` in defaults package
    - "{{ pin_compatible('brotli', max_pin='x.x') }}"
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
  # TODO: add these tests when we start to include builds with turbo
  # files:
  #     - 687px-Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg
  #     - ensure_jpegturbo_imagecodecs_plays_nicely_with_jpeg9.py
  # requires:
  #   - pillow
  #   - opencv
  imports:
    - imagecodecs
    - imagecodecs._imagecodecs
  commands:
    - pip check
    - cd tests
      # TODO: determine why OpenMP on Windows build workers is unreliable
    - set SKIP_OMP=true                 [win]
    # https://github.com/conda-forge/imagecodecs-feedstock/pull/32#issuecomment-863041029
    - pytest -vv test_imagecodecs.py -k "not test_image_roundtrips[jpeg2k-uint16-rgb-out-bytearray-None]"  #[not s390x]
    - pytest -vv test_imagecodecs.py -k "not test_image_roundtrips[jpeg2k-uint16-rgb-out-bytearray-None] and not test_packints_decode and not test_floatpred and not test_float24 and not test_jpegsof3 and not test_image_roundtrips"  #[s390x]

    # CAPTURING FAILING S390x tests to be reviewed later (These tests are failing most likely from an upstream Endianess issue)
    # These may be fixed with future versions but needs to be checked.
    - pytest -vv test_imagecodecs.py -k "test_packints_decode and test_floatpred and test_float24 and test_jpegsof3 and test_image_roundtrips" || true  #[s390x]

  #   - python ensure_jpegturbo_imagecodecs_plays_nicely_with_jpeg9.py 0
  #   - python ensure_jpegturbo_imagecodecs_plays_nicely_with_jpeg9.py 1

about:
  home: https://www.cgohlke.com
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - 3rdparty/liblzf/LICENSE
    - 3rdparty/bitshuffle/LICENSE
    - 3rdparty/openjpeg/LICENSE
  summary: Image transformation, compression, and decompression codecs
  description: |
    The imagecodecs package provides various block-oriented, in-memory buffer
    transformation, compression, and decompression functions for use in the
    tifffile, czifile, and other Python imaging modules.

    Decode and/or encode functions are currently implemented for Zlib DEFLATE,
    ZStandard, Blosc, LZMA, BZ2, LZ4, LZW, LZF, PNG, WebP, JPEG 8-bit,
    JPEG 12-bit, JPEG SOF=0xC3, JPEG 2000, JPEG XR, PackBits, Packed Integers,
    Delta, XOR Delta, Floating Point Predictor, and Bitorder reversal.

  doc_url: https://www.cgohlke.com
  dev_url: https://github.com/cgohlke/imagecodecs

extra:
  recipe-maintainers:
    - csachs
    - hmaarrfk
    - sdvillal
